import React from 'react';

function Student_suggsol()
{
    return (
        <div>
            <div style={{marginLeft:"20%"}}>
        <div className="content">
          <span><a href="detail_soln.html "><b>UX problem statement</b><br/>Users of our proposal software have reported frustration at having to copy information into the CRM after they send a proposal. They use their CRMs to track all email conversations, phone calls, and other lead and client interactions. Without CRM integrations, our proposal software causes a frustrating experience for our power users. While users from very small businesses and firms don’t have this issue, we are hearing from sales reps at SMBs and enterprises that the need to duplicate proposal sending information in their CRM causes an additional two to three hours of work every week. The problem is that we don’t have any integrations with CRMs and we have not yet identified the CRMs of our best users. We need to send segmented surveys to determine our priorities for the first three CRMs to integrate with, and we need to build in the user flows around these integrations</a></span>
          <span><a href="#not"><b>Digital transformation problem statement</b><br/>We are in need of a faster and more secure way to onboard and offboard employees. Our current processes require hiring managers to ask the security team for the same tasks over and over, and for the security team to hand over repetitive tasks to IT. We need to use automation to address repetitive tasks for onboarding, such as granting access to platforms and devices and during offboarding when revoking access. We also need a solution to address security concerns when employees lose their devices. We need a proprietary solution that is perfectly customized to our needs. The cost of custom solutions will be evaluated against their ability to save time for high-wage employees (security and IT). No former attempts have been made to resolve these issues with automation and custom coding.</a></span>
          <span><a href="#not"><b>Problem statement for IT</b><br/>We have had a no-working-from home policy in effect for all staff members of our school district since its founding date. However, in light of recent events (the prevalence of working from home in the aftermath of the Covid-19 pandemic) and after witnessing 3 neighboring school districts allowing some form of work from home, we feel that we can no longer disallow all forms of working from home. Our office staff members have been complaining about our policy for the past 3 years. We are concerned that we will not be able to hire new quality staff members, who may prefer to apply at one of our neighboring school districts. We are also concerned about losing our current staff members to one of these districts.
              <br/>We feel that it is now essential to offer some form of working from home. To start, we would like to only allow staff to work from home when they are sick (with minimal symptoms) or quarantining from Covid-19. Many staff members will feel perfectly healthy, but have to stay home due to our continued 14-day quarantine policy. This causes major delays and challenges among the office staff, who are short staffed as it is.
              <br/>To solve this problem, we will need to provide secure access to MicroSoft Teams and the other cloud computing software that office staff use. We may need to provide them with district-issued devices to ensure the security of our data when staff are working from home. Our IT department will further assess these problems and come up with a solution to allow staff to work from home. After piloting this policy for quarantine days only, we may consider permitting one day of work from home per week, however this will not be announced to staff until after the initial pilot is successful.
              <br/>This problem needs to be resolved by July, in order to permit working from home for the coming school year. The current severity of this problem is low, but it has a potential to impact security and productivity at a high level.</a>
          </span>
          <span><a href="#not"><b>Problem statement for a new SaaS venture</b><br/>Hiring managers and recruiters are plagued with dozens of repetitive, boring tasks across the hiring process, including screening applicants, reaching out to applicants to schedule interviews, managing rescheduling and cancellations, answering questions for applicants at a variety of stages during the hiring process. Whether for hourly positions or professional positions, the hiring process still requires a lot of manual work. This makes recruiters’ and hiring managers’ daily lives boring and monotonous, taking away from the fun part of their jobs, which is meeting new people and assessing how they will fit into various company cultures and specific roles. Great hirers truly want to put the right people in the right positions and don’t have enough assistance with the boring tasks to allow them to focus on what matters. We expect to resolve this issue through the use of AI. Competitor products provide software tools to digitize this work, but don't offer AI solutions to drastically cut down on this work.</a></span>
          <span><a href="#not"><b>Business problem statement</b><br/>Our real estate investing intelligence software has experienced a downfall or a plateau in paid subscription purchases every month for the past 5 months, even though our benchmark for free trial sign ups has remained steady. This means that our business isn't facing a traffic issue, but rather a conversion issue. This problem could be to a variety of related problems, including recently raised interest rates for mortgages in the United States, the overall slowing of the real estate market, as well as factors that we can control within our business. Some of the factors we can control include our onboarding flow for new users within the platform, our video tutorials, our reocurring live workshops, and our email onboarding sequence. Part of the problem may also be with our pricing. We have identified that we receive a lack of paid subscriptions and a lot of churn because users are able to get too much value out of our free plan. We likely need to restructure our free trial to offer less value so that users are required to sign up for a paid plan to download a list of leads of real estate deals. However, this will not resolve our churn problem, as we get 50% of new paying users churning after their first month. We need to build additional features to keep real estate investors staying with our platform for at least 4 months.</a></span>
        </div>
        </div>
        </div>
    )
};
export default Student_suggsol;